# Generated by Django 3.2.10 on 2022-10-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='np_phone',
            new_name='np_account',
        ),
        migrations.AddField(
            model_name='account',
            name='np_address_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='np_city_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='np_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='np_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
