# Generated by Django 3.2.10 on 2022-10-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20221016_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='np_account',
            new_name='npToken',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='np_account_ref',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='np_address_ref',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='np_address',
            new_name='senderDepartmentAddress',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='np_api_key',
            new_name='senderDepartmentAddressRef',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='np_city',
            new_name='senderDepartmentCity',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='np_city_ref',
            new_name='senderDepartmentCityRef',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='phone_num',
            new_name='senderRef',
        ),
    ]
