# Generated by Django 3.2.10 on 2022-10-21 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Added at')),
                ('PayerType', models.CharField(choices=[('Recipient', 'Отримувач'), ('Sender', 'Відправник')], default='Recipient', max_length=50)),
                ('PaymentMethod', models.CharField(choices=[('Cash', 'Готівка'), ('NonCash', 'Безготівка')], default='Cash', max_length=50)),
                ('DateTime', models.DateTimeField(auto_now_add=True, verbose_name='Added at')),
                ('CargoType', models.CharField(choices=[('Cargo', 'Вантаж'), ('Documents', 'Документи')], default='Cargo', max_length=50)),
                ('VolumeGeneral', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ServiceType', models.CharField(max_length=50)),
                ('SeatsAmount', models.PositiveIntegerField()),
                ('Description', models.CharField(max_length=200)),
                ('Cost', models.PositiveIntegerField(verbose_name='Assessed value')),
                ('RecipientName', models.CharField(max_length=50)),
                ('RecipientSurname', models.CharField(max_length=50)),
                ('CityRecipient', models.CharField(max_length=100)),
                ('RecipientAddress', models.CharField(max_length=100)),
                ('Recipient', models.CharField(max_length=100)),
                ('ContactRecipient', models.CharField(max_length=100)),
                ('RecipientsPhone', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_owner', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['id'],
            },
        ),
    ]
