# Generated by Django 3.2.10 on 2022-10-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='DateTime',
            field=models.DateTimeField(verbose_name='Added at'),
        ),
    ]
