# Generated by Django 3.2.10 on 2022-10-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='VolumeGeneral',
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
    ]
